import '@/styles/globals.css'

import { Nunito } from 'next/font/google'

const nunito = Nunito({
  weight: '300',
  subsets: ['latin'],
  display: 'swap',
  adjustFontFallback: false //when fallback dont let get the fonts from google
})

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }) {
  return (
    <main>
      <Component {...pageProps} />
    </main>
  )
}
