import '@/styles/globals.css'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function App({ Component, pageProps }) {
  return (
    <main>
      <Component {...pageProps} />
    </main>
  )
}
